### ISSUE TITLE
The problem named "Check failed: error" appears, would you tell me some clues to solve it?

### ISSUE THREAD

**Issue by TracelessLe** [shurans/sscnet#8]
Hi, @shurans. Could you spare any time to offer clues on the problem below? The problem named "Check failed: error" appears when I train the SSCNet on SUNCG dataset. 
The exception show as below:

> I0309 09:35:32.485882 15771 solver.cpp:228] Iteration 89, loss = 1.78934
> I0309 09:35:32.485936 15771 solver.cpp:244]     Train net output #0: loss = 1.58742 (* 1 = 1.58742 loss)
> I0309 09:35:37.568156 15771 sgd_solver.cpp:106] Iteration 89, lr = 0.01
> F0309 09:35:43.096343 15777 suncg_fusion.hpp:356] Check failed: error == cudaSuccess (2 vs. 0)  out of memory
> *** Check failure stack trace: ***
>     @     0x7fe8e528a5cd  google::LogMessage::Fail()
>     @     0x7fe8e528c433  google::LogMessage::SendToLog()
>     @     0x7fe8e528a15b  google::LogMessage::Flush()
>     @     0x7fe8e528ce1e  google::LogMessageFatal::~LogMessageFatal()
>     @     0x7fe8e5ab1580  ComputeTSDF<>()
>     @     0x7fe8e5ab5e40  caffe::SuncgDataLayer<>::load_batch()
>     @     0x7fe8e59fb3df  caffe::BasePrefetchingDataLayer<>::InternalThreadEntry()
>     @     0x7fe8e5a49f95  caffe::InternalThread::entry()
>     @     0x7fe8db8a95d5  (unknown)
>     @     0x7fe8d63836fa  start_thread
>     @     0x7fe8e3b07b5d  clone
>     @              (nil)  (unknown)
> Aborted (core dumped)

I have searched for some methods to solve the problem.
First, I check the "train_net.txt", the batch_size is 1 which cannot be smaller. 
Then I check the "train.sh" for the information of GPU to run, the machine in the paper is Tesla K40 while our GPU is Titan X (12GB *4) and work fine. I have try some times and find that the problem always appers in the line named "suncg_fusion.hpp". I have no idea how to solve the problem and wonder have you ever met the problem in your Tesla K40?
Thanks for your reply!

**Comment by shurans** [comment]
Seem that you don't have enough free GPU memory when you are running this program. You can use "nvidia-smi" to check the GPU usage.

**Comment by CJohnny** [comment]
@TracelessLe I switch to gtx1070 from gtx950, and this 'core dumped' problem is solved

**Comment by TracelessLe** [comment]
@shurans @CJohnny  I checked the GPU usage and found the memory left is almost 12GB before I run the script, but the "core dumped" problem still appears in the line "suncg_fusion.hpp" and show the message "ComputeTSDF<>(), ...". It's so werid. :-(

**Comment by KnightOfTheMoonlight** [comment]
@shurans So there's no way to reduce the batch size? I found that it seems the batch size is already be 1 from  this https://github.com/shurans/sscnet/blob/ded2781fa13874e757c6fc0d6b2c71f2df5a2394/caffe_code/script/train/ftnyucad/train_net.txt#L82
